"""empty message

Revision ID: 39e2ca918d3c
Revises: 4d52a6a8ff7c
Create Date: 2022-05-18 17:44:43.794144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e2ca918d3c'
down_revision = '4d52a6a8ff7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
