"""empty message

Revision ID: 4ee5e310de65
Revises: 39e2ca918d3c
Create Date: 2022-05-18 17:46:11.512908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee5e310de65'
down_revision = '39e2ca918d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
