"""empty message

Revision ID: 519de2e37be4
Revises: 4ee5e310de65
Create Date: 2022-05-18 17:49:29.799753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519de2e37be4'
down_revision = '4ee5e310de65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
