"""empty message

Revision ID: 6be1dbdb0011
Revises: 4caef0920491
Create Date: 2022-04-10 12:50:10.821816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be1dbdb0011'
down_revision = '4caef0920491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_data')
    # ### end Alembic commands ###
