from enum import Enum


class ProjectState(Enum):
    PRE_DEVELOPMENT = 'PRE_DEVELOPMENT'
    DEVELOPMENT_DESIGN = 'DEVELOPMENT_DESIGN'
    DESIGN_AGREEMENT = 'DESIGN_AGREEMENT'
    DEVELOPMENT_LAYOUT = 'DEVELOPMENT_LAYOUT'
    LAYOUT_AGREEMENT = 'LAYOUT_AGREEMENT'
    AGREEMENT = 'AGREEMENT'
    READY = 'READY'
    NEXT = 'NEXT'
